###1
POST http://localhost:8000/user/register
Content-Type: application/json

[
    {
        "email": "anna@email.com",
        "name": "Anna ",
        "password": "234569"
    },
    {
        "username": "belen@email.com",
        "name": "Belen",
        "password": "345678"
    },
    {
        "username": "johnconway@email.com",
        "name": "John",  
        "password": "234567"
    },
    {
       "username": "addmax@email.com",
        "name": "Mac",  
        "password": "298567" 
    }
]

###2
POST http://localhost:8000/user/authenticate

[
    {
        "email": "anna@email.com",
        "password": "234569"
    },
    {
        "username": "belen@email.com",
        "password": "345678"
    },
    {
        "username": "johnconway@email.com",
        "password": "234567"
    },
    {
       "username": "addmax@email.com", 
        "password": "298567" 
    }
]

###3
GET http://localhost:8000/user/users 

###4
GET http://localhost:8000/user/user/:email

[
    {
        "email": "anna@email.com"
    },
    {
        "email": "belen@email.com"
    },
    {
        "email": "johnconway@email.com"
    },
    {
       "email": "addmax@email.com"
    }
]

###5
DELETE http://localhost:8000/user/user/:email
[
    {
        "email": "anna@email.com"
    },
    {
        "email": "belen@email.com"
    },
    {
        "email": "johnconway@email.com"
    },
    {
       "email": "addmax@email.com"
    }
]



###
PATCH  http://localhost:8000/user/user
Content-Type: application/json

{
  "username": "johnconway@email.com",
  "name": "John",  
  "pasword": 988888
}