###
POST http://localhost:8000/user
Content-Type: application/json

[
    {
        "email": "anna@email.com",
        "name": "Anna ",
        "pasword": 123456
    },
    {
        "username": "belen@email.com",
        "name": "Belen",
        "pasword": 193456
    },
    {
        "username": "johnconway@email.com",
        "name": "John",  
        "pasword": 234567
    }
]

###
GET http://localhost:8000/user/users 

###
GET http://localhost:8000/user/user

###
DELETE http://localhost:8000/user/user

###
PUT http://localhost:8000/user/user
Content-Type: application/json

{
  "username": "johnconway@email.com",
  "name": "John",  
  "pasword": 988888
}